server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Toutes les routes non trouvées retombent sur index.html (React Router gère le routage côté client)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
